on:
  push:
    branches: main
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          # Required, workflow file name or ID
          workflow: rcmd-check.yml
          #workflow_conclusion: completed
          branch: main
          #check_artifacts: true
          #run_id: 1870829721
          #
          # /Users/runner/work/mlr3extralearners/mlr3extralearners/Linux-rrelease-results/mlr3extralearners.Rcheck/tests/testthat.Rout
          #
      - name: list artifacts
        run: |
          ls /Users/runner/work/mlr3extralearners/mlr3extralearners/Linux-rrelease-results/mlr3extralearners.Rcheck/tests

      # - name: echo the file
      #   run: |
      #     cat /Users/runner/work/mlr3extralearners/mlr3extralearners/Linux-rrelease-results/mlr3extralearners.Rcheck/tests/testthat.Rout
      # - uses: r-lib/actions/setup-r@master

